### ISSUE TITLE
How to keep conceding before mulligan?

### ISSUE THREAD

**Issue by dch0319** [ElektroStudios/SmartBotKit#2]
There being an area in unranked standard where people concede to each other, i would like to know how to keep conceding in order to save time.

**Comment by ElektroStudios** [comment]
@dch
Hi. Sorry for the delay!

I think I don't understand what exactly do you mean at all. Can you please add more details if this is a feature request?. Do you want to automatically concede games when matching specific players / battletag names, is that what do you mean?. In that case I could implement that feature in **Advanced Auto-Concede** plugin, but please confirm.

Anyways conceding before mulligan seems not possible since (If I'm not wrong) the SmartBot API does not provide a handler for that game event.

**Comment by dch0319** [comment]
In China,players use bots to keep conceding to decrease MMR. Soon afterwards an area was formed where all players concede to each other before mulligan.So we can easily get 100 gold in 40-60mininutes.I want to automatically concede games no matter who i match.

**Comment by ElektroStudios** [comment]
Feature added in [release 3.9](https://github.com/ElektroStudios/SmartBotKit/releases/tag/v3.9)

To achieve what you need, just check the '**Always concede**' option in the 'AdvancedAutoConcede' plugin. By enabling this option the plugin will automatically concede games no matter who you match.

If you still have any question or request about this feature, please open a new issue.

Thanks for contribute.
